# Generated by Django 4.2.30 on 2026-05-25 09:53

import uuid

from django.db import migrations, models
import django.db.models.deletion
import iot.models


def backfill_access_tokens(apps, schema_editor):
    Device = apps.get_model("iot", "Device")
    for device in Device.objects.filter(access_token__isnull=True):
        device.access_token = uuid.uuid4().hex
        device.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="telemetryrecord",
            name="device",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="enabled",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="device",
            name="host",
        ),
        migrations.RemoveField(
            model_name="device",
            name="poll_interval",
        ),
        migrations.RemoveField(
            model_name="device",
            name="port",
        ),
        migrations.RemoveField(
            model_name="device",
            name="protocol",
        ),
        migrations.RemoveField(
            model_name="device",
            name="slave_id",
        ),
        migrations.AddField(
            model_name="device",
            name="access_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_access_tokens, migrations.RunPython.noop),
        migrations.AddField(
            model_name="device",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="access_token",
            field=models.CharField(
                default=iot.models.generate_access_token, max_length=64, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="RegisterMap",
        ),
        migrations.DeleteModel(
            name="TelemetryRecord",
        ),
        migrations.AddField(
            model_name="telemetrydata",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telemetry",
                to="iot.device",
            ),
        ),
        migrations.AddField(
            model_name="telemetrydata",
            name="sensor_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telemetry",
                to="iot.sensortype",
            ),
        ),
        migrations.AddIndex(
            model_name="telemetrydata",
            index=models.Index(
                fields=["device", "timestamp"], name="iot_telemet_device__899402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetrydata",
            index=models.Index(
                fields=["timestamp"], name="iot_telemet_timesta_14457e_idx"
            ),
        ),
    ]
